// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Platform.Api.Data;

#nullable disable

namespace Platform.Api.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260301120000_AddRefreshTokens")]
    partial class AddRefreshTokens
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Platform.Api.Data.RefreshToken", b =>
            {
                b.Property<Guid>("TokenId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("Device")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTimeOffset>("ExpiresAt")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid?>("ReplacedByTokenId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset?>("RevokedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("TokenHash")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("TokenId");

                b.HasIndex("TenantId", "UserId");

                b.HasIndex("UserId", "TokenHash")
                    .IsUnique();

                b.ToTable("RefreshTokens");
            });
        }
    }
}
