// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Platform.Api.Data;

#nullable disable

namespace Platform.Api.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260302070000_AddStudioEntities")]
    partial class AddStudioEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally minimal; runtime uses the Up/Down methods.
        }
    }
}
